language: go
go_import_path: github.com/kamiazya/go-dispatcher

go:
  - 1.8.x
  - 1.9.x
  - tip

before_install:
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
