// Code generated by "stringer -type=LifeCycle"; DO NOT EDIT.

package dispatcher

import "fmt"

const _LifeCycle_name = "InitialStartedStoped"

var _LifeCycle_index = [...]uint8{0, 7, 14, 20}

func (i LifeCycle) String() string {
	if i < 0 || i >= LifeCycle(len(_LifeCycle_index)-1) {
		return fmt.Sprintf("LifeCycle(%d)", i)
	}
	return _LifeCycle_name[_LifeCycle_index[i]:_LifeCycle_index[i+1]]
}
